// Auto-generated by convert_tiles.py — DO NOT EDIT
#ifndef METATILES_H
#define METATILES_H

#define MT_PALETTE_SIZE 52
#define MT_TILE_COUNT 81
#define MT_COUNT 10

#define MT_GROUND_GRASS 0
#define MT_GROUND_STONE 1
#define MT_GROUND_DIRT 2
#define MT_GROUND_WATER 3
#define MT_GROUND_ROOF 4
#define MT_SIDE_GRASS_EDGE 5
#define MT_SIDE_STONE_WALL 6
#define MT_SIDE_DIRT_WALL 7
#define MT_SIDE_BRICK_WALL 8
#define MT_SIDE_ROOF_EDGE 9

extern const unsigned short mt_palette[];
extern const unsigned char mt_tile_pixels[][64];
extern const unsigned short mt_metatile_tiles[][8];

#endif // METATILES_H
